import type { IndustryTemplate } from "../types";

// Industry presentation templates. They reference existing catalog problems,
// module types, dashboard cards, and integrations — applying one creates a
// NEW presentation and never overwrites a saved custom presentation.

const t = (
  industryId: string,
  name: string,
  commonProblems: string[],
  discoveryQuestions: string[],
  recommendedModules: IndustryTemplate["recommendedModules"],
  defaultCurrentWorkflow: string[],
  defaultProposedWorkflow: string[],
  suggestedDashboards: string[],
  typicalIntegrations: string[],
  suggestedNextStep: IndustryTemplate["suggestedNextStep"] = "discovery-workshop",
): IndustryTemplate => ({
  industryId,
  name,
  commonProblems,
  discoveryQuestions,
  recommendedModules,
  defaultCurrentWorkflow,
  defaultProposedWorkflow,
  demoSequence: recommendedModules,
  suggestedDashboards,
  typicalIntegrations,
  suggestedNextStep,
});

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  t("retail", "Retail",
    ["stock-inaccurate", "lowstock-late", "sales-unclear", "no-loyalty"],
    ["How do you count and reorder stock today?", "How many branches and who watches their numbers?", "How do you know what sold well this week?", "What happens when an item runs out?"],
    ["inventory", "ordering", "dashboard", "membership"],
    ["Count stock by notebook", "Text the supplier", "Wait for delivery", "Discover stock-outs at the counter"],
    ["Live stock list with alerts", "PO raised from reorder list", "Delivery received in system", "Dashboard shows branch sales"],
    ["total-sales", "low-stock", "branch-perf", "pending-po"],
    ["sms", "excel", "barcode", "pos"]),
  t("wholesale", "Wholesalers & Distributors",
    ["duplicate-data-entry", "payment-status-unclear", "transfers-hard", "no-realtime-visibility"],
    ["How do dealers place orders today?", "Who tracks receivables and how?", "How do you monitor warehouse against sales?", "Which reports do you build by hand?"],
    ["ordering", "inventory", "billing", "portal", "dashboard"],
    ["Orders by call and Viber", "Encode into Excel", "Warehouse checks stock manually", "Collections chased from memory"],
    ["Dealer portal order", "Stock auto-checked", "Delivery scheduled", "Receivables dashboard"],
    ["total-sales", "overdue", "low-stock", "delivery"],
    ["viber", "excel", "accounting", "sms"]),
  t("food", "Restaurants & Cafés",
    ["stock-inaccurate", "appointments-missed", "reports-take-hours", "no-loyalty"],
    ["How do you track ingredient usage?", "How do reservations reach the kitchen?", "How do branches report daily sales?", "Do regulars get anything for coming back?"],
    ["inventory", "booking", "dashboard", "membership"],
    ["Ingredients counted by feel", "Reservations in a notebook", "Sales totals texted nightly", "No record of regulars"],
    ["Ingredient levels with alerts", "Reservations on one calendar", "Branch dashboard live", "Loyalty points at the counter"],
    ["total-sales", "low-stock", "appointments", "branch-perf"],
    ["messenger", "pos", "excel"]),
  t("hospitality", "Hotels & Tourism",
    ["appointments-missed", "customers-ask-updates", "assignments-unclear", "no-realtime-visibility"],
    ["Where do bookings come from and who records them?", "How does housekeeping know what to clean?", "How do guests ask questions?", "How do you see occupancy at a glance?"],
    ["booking", "tasks", "maintenance", "dashboard"],
    ["Bookings in a logbook", "Housekeeping told verbally", "Guests call the desk repeatedly", "Occupancy computed weekly"],
    ["Bookings in one calendar", "Housekeeping task board", "Guest updates simulated", "Occupancy dashboard"],
    ["appointments", "csat", "tickets", "branch-perf"],
    ["email", "gcal", "webforms"]),
  t("realestate", "Real Estate",
    ["leads-forgotten", "followups-inconsistent", "docs-incomplete", "customers-ask-updates"],
    ["Where do buyer inquiries come from?", "How do agents track follow-ups?", "How do you track requirements per buyer?", "How do you monitor agent performance?"],
    ["crm", "booking", "documents", "dashboard"],
    ["Inquiries in personal phones", "Follow-ups from memory", "Requirements in folders", "Status asked agent by agent"],
    ["Leads captured with owners", "Tripping schedule shared", "Document checklist per buyer", "Agent pipeline dashboard"],
    ["new-leads", "conversion", "doc-exp", "appointments"],
    ["fbleads", "webforms", "sms", "gcal"]),
  t("construction", "Construction",
    ["quotations-slow", "job-status-hard", "stock-inaccurate", "approvals-in-chat"],
    ["How long does a quotation take today?", "How do you monitor site progress?", "How are materials requested and released?", "How are changes approved?"],
    ["quotation", "projects", "inventory", "approvals"],
    ["Estimate in Excel", "Site updates by call", "Materials on trust", "Approvals in group chat"],
    ["Itemized quotation", "Project board with photos concept", "Materials issued per project", "Documented change approvals"],
    ["open-jobs", "pending-quotes", "low-stock", "pending-po"],
    ["excel", "sms", "csv"]),
  t("professional", "Professional Services",
    ["work-tracked-manually", "docs-incomplete", "followups-inconsistent", "payment-status-unclear"],
    ["How do engagements move from inquiry to completion?", "How do you chase client documents?", "How do deadlines get tracked?", "How do you know who owes you?"],
    ["crm", "projects", "documents", "billing"],
    ["Inquiries in email threads", "Deadlines in personal calendars", "Documents chased by text", "Billing from memory"],
    ["Client pipeline", "Engagement deadlines tracked", "Document checklist per client", "Billing status list"],
    ["new-leads", "open-jobs", "doc-exp", "overdue"],
    ["email", "gdrive", "gcal"]),
  t("automotive", "Automotive",
    ["work-tracked-manually", "customers-ask-updates", "stock-inaccurate", "no-reminders"],
    ["How does a car move from intake to release?", "How do customers learn their car is ready?", "How are parts tracked?", "Do customers return for maintenance?"],
    ["booking", "projects", "inventory", "quotation"],
    ["Job orders on paper", "Customer calls for status", "Parts found by walking the shelf", "No return reminders"],
    ["Appointment to job order", "Status updates simulated", "Parts inventory with alerts", "Maintenance reminders concept"],
    ["open-jobs", "appointments", "low-stock", "csat"],
    ["sms", "messenger", "barcode"]),
  t("beauty", "Beauty & Wellness",
    ["appointments-missed", "no-loyalty", "schedules-conflict", "no-reminders"],
    ["How do clients book today?", "How do you fill quiet hours?", "How are stylists scheduled?", "How do you bring clients back?"],
    ["booking", "membership", "scheduling", "dashboard"],
    ["Bookings in Messenger", "No-shows unmanaged", "Stylist schedule on whiteboard", "Regulars untracked"],
    ["Online booking calendar", "Simulated reminders cut no-shows", "Stylist shifts planned", "Loyalty packages tracked"],
    ["appointments", "csat", "total-sales", "attendance"],
    ["messenger", "sms", "fbleads"]),
  t("fieldservice", "Home & Field Services",
    ["field-staff-hard", "quotations-slow", "customers-ask-updates", "no-reminders"],
    ["How are jobs dispatched to technicians?", "How do quotes reach customers?", "How do customers track their request?", "What happens after a job is done?"],
    ["booking", "quotation", "delivery", "projects"],
    ["Jobs assigned by call", "Quotes computed on site", "Customers call for updates", "No after-service follow-up"],
    ["Booked jobs dispatched", "Quotation from standard items", "Status visible per job", "Follow-up reminders concept"],
    ["open-jobs", "appointments", "delivery", "csat"],
    ["sms", "webforms", "gcal"]),
  t("church", "Churches & Ministries",
    ["customer-info-scattered", "followups-inconsistent", "assignments-unclear", "no-realtime-visibility"],
    ["How do you follow up with first-time visitors?", "How are volunteers scheduled?", "How do small groups report?", "What does leadership see monthly?"],
    ["crm", "membership", "scheduling", "universal"],
    ["Visitor slips in a box", "Follow-up when remembered", "Volunteer lineup by group chat", "Reports compiled manually"],
    ["Visitor follow-up pipeline", "Membership records", "Volunteer schedule", "Ministry dashboard"],
    ["new-leads", "attendance", "csat", "branch-perf"],
    ["messenger", "sms", "gsheets"]),
  t("training", "Training & Coaching",
    ["work-tracked-manually", "payment-status-unclear", "no-customer-history", "followups-inconsistent"],
    ["How do participants register and pay?", "How do you track attendance and completion?", "How do you sell the next program to alumni?", "Which admin work eats your week?"],
    ["learning", "billing", "crm", "membership"],
    ["Registration by form + chat", "Attendance on paper", "Payments tracked in Excel", "Alumni list unused"],
    ["Online registration", "Attendance & completion tracked", "Payment status list", "Alumni follow-up pipeline"],
    ["new-leads", "total-sales", "overdue", "csat"],
    ["email", "gsheets", "webforms"]),
];

export function getTemplate(industryId: string): IndustryTemplate | undefined {
  return INDUSTRY_TEMPLATES.find((x) => x.industryId === industryId);
}
