import type { ObjectionEntry } from "../types";

export const OBJECTION_DISCLAIMER =
  "Internal presenter guidance only — never show this screen to clients. Verify technical claims before promising them.";

const o = (
  id: string,
  question: string,
  recommendedResponse: string,
  askTheClient: string[],
  verifyTechnically: string,
  overpromiseRisk: string,
  commercialModel: string,
  scopeDisclaimer: string,
): ObjectionEntry => ({ id, question, recommendedResponse, askTheClient, verifyTechnically, overpromiseRisk, commercialModel, scopeDisclaimer });

export const OBJECTION_GUIDE: ObjectionEntry[] = [
  o("why-not-excel", "Why not continue using Excel?",
    "Excel is great for one person and one file. The problems start with many hands: overwritten versions, no history, no reminders, nothing happens by itself. A system adds accountability and automation on top of the data.",
    ["How many people edit the same sheet?", "What was your last version mix-up?", "Who updates it when the owner is away?"],
    "Nothing — this is a positioning answer.",
    "Don't trash Excel; they'll keep using it for analysis. Position the system as the source of truth, Excel as the export target.",
    "Shared or Configured SaaS", "Excel import/export can be scoped as an optional service."),
  o("why-not-commercial", "Why not use an existing commercial application?",
    "Sometimes you should — and we'll say so if a generic tool fits. Our value is fitting Filipino SME workflows: your terms, your process, peso pricing, local support, and demos you can try before deciding.",
    ["Which apps have you tried and why did they not stick?", "What's the one workflow no generic app handled?"],
    "Compare seriously against the named competitor before the next meeting.",
    "Never claim superiority over a specific product you haven't examined.",
    "Configured SaaS", "A comparison, if requested, is an internal analysis, not a guarantee."),
  o("phones", "Can employees use it on their phones?",
    "Yes — everything you've seen today is running on a phone-first design; it installs like an app and the demo works offline. Production behavior on your team's exact devices is confirmed during deployment.",
    ["What phones does your team actually use?", "Any staff without smartphones?"],
    "Device compatibility for low-end Android units in actual use.",
    "Don't promise iOS/Android feature parity for camera/scanner hardware without checking.",
    "Any", "Device compatibility is verified during deployment."),
  o("offline", "Can it work offline?",
    "This demo works fully offline — you saw it. For production, viewing cached data offline is realistic; editing offline with multiple users needs careful design and honest scoping.",
    ["Where is connectivity weakest — branches or field staff?", "What must work during an outage: viewing or entering data?"],
    "Offline-editing requirements need a technical assessment — sync conflicts are genuinely hard.",
    "HIGH RISK: do not promise full offline editing with automatic sync. That is a major engineering commitment.",
    "Custom-built for serious offline needs", "Offline behavior beyond cached viewing requires technical assessment."),
  o("multi-branch", "Can it support multiple branches?",
    "Yes — branch visibility is one of the core reasons SMEs adopt this. You saw branch dashboards and per-branch stock. Branch count affects pricing, which the estimate already shows transparently.",
    ["How many branches now, and in two years?", "Do branches share stock or customers?"],
    "Data-separation rules per branch (who may see what).",
    "Cross-branch permission subtleties need confirmation before contract.",
    "Configured SaaS or Custom", "Per-branch pricing is in the estimate; permissions confirmed in scope."),
  o("source-code", "Can the client own the source code?",
    "Yes, through the Exclusive Build option — full development cost plus source-code and exclusivity premiums, documented in the pricing configurator. Most clients find Configured SaaS more economical; ownership matters most for strategic systems.",
    ["Why is ownership important — control, exit risk, or resale?", "Who would maintain it after handover?"],
    "Licensing of third-party components in a transfer.",
    "Don't promise transfer terms — those are contractual, drafted case by case.",
    "Exclusive build with source-code transfer", "Transfer terms per signed agreement only."),
  o("add-later", "Can features be added later?",
    "Yes — that's the design. Start with the modules that hurt most; add modules or move up a configuration level later. The demo hub itself shows every module ready to be switched on conceptually.",
    ["Which single module would you start with?", "What's the 6-month wish list?"],
    "Nothing for module additions; custom features need assessment.",
    "Later additions are re-estimated at then-current pricing — say so now.",
    "Any", "Future phases are estimated separately when scoped."),
  o("security", "How secure is it?",
    "Walk them through the Security & Privacy screen: expected production foundations (authentication, roles, encryption, backups) vs. items needing assessment. Then be honest: this demo proves workflows, not security — production security is designed, tested, and confirmed contractually.",
    ["What data worries you most?", "Any compliance obligations (privacy, industry rules)?"],
    "Everything on the security screen marked 'assessment' or 'not yet verified'.",
    "SEVERE: never claim compliance with any law, standard, or certification without explicit verification.",
    "Any", "The Security screen's disclaimer applies verbatim."),
  o("internet-down", "What happens when the internet is unavailable?",
    "The installed app still opens and shows cached information — like this demo. New entries during an outage are a design decision: some clients queue paper for an hour, others need offline entry, which we scope explicitly.",
    ["How often and how long are your outages?", "What absolutely cannot stop during one?"],
    "Same as offline: anything beyond cached viewing needs assessment.",
    "Same trap as the offline question — don't wave it away.",
    "Any", "Outage behavior is defined in the technical design."),
  o("integrate-existing", "Can it integrate with an existing system?",
    "Often yes, and the Integrations screen shows what each connection involves honestly. The first step is always a short technical assessment: does the system have an API, who owns the account, what data moves which way.",
    ["What system, and who set it up?", "Do you have API documentation or a vendor contact?"],
    "Run the integration-assessment questionnaire before any commitment.",
    "Never say 'yes, easy integration' before the assessment — this is a classic overpromise.",
    "Depends on the integration", "Integrations are scoped only after assessment."),
  o("why-custom-expensive", "Why is custom-built more expensive?",
    "With SaaS, many businesses share a platform's cost. Custom means one client funds everything: design, development, testing, deployment, and its future maintenance. That's worth it when workflows are genuinely unique — the delivery-model comparison shows the trade honestly.",
    ["Which of your workflows do you believe no shared platform can handle?", "Is that workflow stable or still changing?"],
    "Whether their 'unique' workflow is actually unique — it often isn't.",
    "Don't undersell custom to win a deal — underpriced custom projects fail.",
    "Custom-built", "Custom pricing is preliminary until scope is signed."),
  o("support", "What support is included?",
    "Show the Support Plans screen: channels, hours, response targets, and monthly fees per tier — with response targets explicitly preliminary until the service agreement is signed.",
    ["Who on your side will be the first point of contact?", "What's your realistic expectation when something breaks at 9 PM?"],
    "Any response target beyond the seed values needs owner confirmation.",
    "Response targets are not contractual until the signed agreement — repeat this.",
    "Any", "Support terms per the signed service agreement."),
  o("data-after-end", "What happens to the data if the subscription ends?",
    "Honest answer: the client should get a usable export of their records — that's the plan and it belongs in the contract. Say it, then write it into the agreement rather than leaving it verbal.",
    ["What format would your accountant want the export in?", "Any retention rules for your industry?"],
    "Export formats and retention windows must be defined in the agreement.",
    "Don't improvise retention promises — put them in writing.",
    "SaaS models", "Data-exit terms are contractual, not a demo feature."),
  o("export-reports", "Can reports be exported?",
    "Standard exports (spreadsheet-friendly) are a normal production capability and cheap to scope; the demo shows the reports conceptually. Custom report formats are listed as optional services with prices.",
    ["Which three reports do you actually print or send today?", "Who consumes them — accountant, bank, franchisor?"],
    "Collect sample report formats before committing to replicate them.",
    "'Any report you want' is an overpromise — bound it to samples provided.",
    "Any", "Custom reports priced as optional services from samples."),
  o("start-small", "Can we start with only a few modules?",
    "Absolutely — that's the recommended path, and the Essential package exists exactly for it. Start where it hurts most, prove it, then grow. Small successful starts beat big stalled projects.",
    ["Which one problem, solved next month, would feel like a win?", "Who will champion the system internally?"],
    "Nothing.",
    "None — this answer is safe and usually closes better.",
    "Shared or Configured SaaS, Essential package", "Later modules re-estimated when added."),
  o("customize-later", "Can the system be customized later?",
    "Yes — configuration changes (labels, fields, workflows) are routine; deeper customization moves you up a configuration level with transparent pricing. What to avoid is customizing before the team has even used the standard flow.",
    ["What would you customize on day one, honestly?", "Could that wait sixty days until the team has real usage?"],
    "Deep customizations need the same assessment as new features.",
    "Unlimited-customization implications sink projects — anchor to the configuration levels.",
    "Configured SaaS and above", "Customizations estimated per the configuration-level rules."),
];
