import type { DemoScenarioDef } from "../types";

// Reusable demo scenarios: realistic stories the presenter walks through
// inside the existing demo modules. "Launch" opens the matching demo; the
// steps below are the presenter's script. Resetting the demo module restores
// its seed records (standard demo reset behavior).

const s = (
  id: string,
  title: string,
  type: string,
  modules: DemoScenarioDef["modules"],
  initialData: string,
  triggerEvent: string,
  roles: string[],
  steps: string[],
  expectedOutcome: string,
  discussionQuestions: string[],
  businessValue: string,
  industries: string[] = [],
): DemoScenarioDef => ({
  id, title, type, industries, modules, initialData, triggerEvent, roles, steps,
  expectedOutcome, discussionQuestions, businessValue,
  resetBehavior: "Use the demo's Reset button to restore the original sample records.",
});

export const SCENARIO_LIBRARY: DemoScenarioDef[] = [
  s("happy-path", "Inquiry to completed job, no surprises", "Happy path", ["crm", "projects"],
    "Seeded leads and job orders in the demo.",
    "A new inquiry arrives from Facebook.",
    ["Salesperson", "Manager", "Customer"],
    ["Create the lead with source Facebook", "Assign it to a salesperson", "Move it to Qualified, then Won", "Open the job demo and create the job", "Progress the job to Completed", "Point out the simulated customer notification"],
    "One inquiry travels to completion with a full history and zero chat archaeology.",
    ["Where does this chain break in your business today?", "Who would own each step here?"],
    "Shows end-to-end accountability — the core promise of the system."),
  s("delayed-approval", "The approval that sits for two days", "Delayed approval", ["approvals", "quotation"],
    "Seeded approval requests, one already Under Review.",
    "A quotation needs the owner's sign-off while they're traveling.",
    ["Staff", "Manager", "Owner"],
    ["Open the pending approval and show its age", "Show the documented queue vs. a buried chat message", "Approve it with a remark", "Show the decision recorded in history"],
    "The bottleneck is visible and the decision is documented instead of vanishing in chat.",
    ["How long do approvals wait today?", "Who is allowed to approve when the owner is away?"],
    "Turns invisible delays into a visible, escalatable queue."),
  s("low-stock", "The stock-out nobody saw coming", "Low-stock problem", ["inventory", "procurement"],
    "Inventory demo seeded with one item at zero and two below reorder level.",
    "A customer asks for an item that just ran out.",
    ["Staff", "Manager"],
    ["Open the inventory demo and show the low-stock banner", "Stock-out one more unit of a low item live", "Show the status flip to Out of Stock", "Open procurement and raise the reorder"],
    "The system flags the shortage days before the customer would have.",
    ["What did your last stock-out cost?", "Who should get the low-stock alert?"],
    "Direct revenue protection — the easiest value to explain."),
  s("missed-appointment", "The no-show that didn't have to happen", "Missed appointment", ["booking"],
    "Booking demo seeded with today's and this week's schedule.",
    "A customer forgets their afternoon appointment.",
    ["Staff", "Customer"],
    ["Show today's schedule with the booking", "Show the simulated reminder that would have gone out", "Mark the booking completed after the 'reminded' customer arrives", "Show the day's status summary"],
    "Reminders convert forgotten bookings into kept ones.",
    ["How many no-shows last month?", "What does an empty slot cost you?"],
    "Recovered appointments are recovered revenue."),
  s("forgotten-lead", "The inquiry that fell through the cracks", "Forgotten lead", ["crm"],
    "CRM demo seeded with leads across pipeline stages.",
    "A week-old inquiry was never answered.",
    ["Salesperson", "Manager"],
    ["Sort the pipeline and find the stale New lead", "Assign it and log the recovery call as a note", "Move it to Contacted", "Show the manager's funnel view"],
    "Stale leads surface automatically instead of dying quietly.",
    ["Where do inquiries land today, and who checks?", "How many quotes died from silence?"],
    "Every recovered lead is money already paid for (marketing) being rescued."),
  s("overdue-payment", "The polite collections routine", "Overdue payment", ["billing"],
    "Billing demo seeded with paid, partial, and overdue accounts.",
    "Month-end shows two accounts past due.",
    ["Admin", "Manager", "Customer"],
    ["Filter to Overdue", "Show the simulated payment-reminder message", "Log a follow-up note on the account", "Mark one account Partial after a promised payment"],
    "Collections become a routine list, not an awkward memory exercise.",
    ["Who follows up on overdue accounts today?", "How much is currently past due?"],
    "Cash-flow visibility and earlier, systematic follow-up."),
  s("complaint", "The complaint that got handled properly", "Customer complaint", ["maintenance", "portal"],
    "Ticket demo seeded with open and resolved tickets.",
    "A customer reports the same issue a second time.",
    ["Customer", "Staff", "Manager"],
    ["Log the complaint as a ticket with High priority", "Show the ticket history proving the earlier report", "Assign and resolve with a resolution note", "Show the customer-visible status concept"],
    "The complaint has an owner, a history, and a resolution — visible to everyone.",
    ["Where do complaints go today?", "How would you know if the same issue keeps repeating?"],
    "Repeat problems become visible patterns instead of anecdotes."),
  s("failed-delivery", "The delivery that bounced", "Failed delivery", ["delivery"],
    "Dispatch demo seeded with deliveries in various stages.",
    "A delivery fails because the customer was out.",
    ["Driver", "Staff", "Customer"],
    ["Mark an in-transit delivery as Failed with a note", "Show it flagged for redelivery", "Reschedule and dispatch again", "Record proof of delivery on success"],
    "Failed deliveries are tracked to resolution instead of lost in phone calls.",
    ["How do you find out a delivery failed today?", "Who pays for the second trip?"],
    "Fewer lost deliveries, documented proof, accountable drivers."),
  s("urgent-service", "The urgent request that jumped the queue", "Urgent service request", ["projects", "booking"],
    "Job demo seeded with a normal-priority queue.",
    "A VIP customer calls with an emergency job.",
    ["Staff", "Manager", "Technician"],
    ["Create the job with Urgent priority", "Show it sorted to the top", "Reassign a technician to it", "Progress it while the routine queue stays visible"],
    "Urgencies are handled without losing track of everything else.",
    ["What happens to the queue when an emergency lands today?", "Who decides what gets bumped?"],
    "Priority handling with zero forgotten regular jobs."),
  s("employee-absence", "The shift with a hole in it", "Employee absence", ["scheduling", "tasks"],
    "Shift demo seeded with this week's schedule.",
    "A staff member calls in sick an hour before opening.",
    ["Staff", "Manager"],
    ["Mark the absent staff on today's shift", "Show the coverage gap", "Assign a replacement", "Reassign the absent person's tasks"],
    "The gap is visible and fixed in minutes, with tasks reassigned, not dropped.",
    ["How do you cover absences today?", "What gets forgotten when someone is out?"],
    "Continuity — the day survives an absence without chaos."),
  s("multi-branch", "Two branches, one picture", "Multi-branch coordination", ["dashboard", "inventory"],
    "Dashboard demo with branch comparison; inventory across branches.",
    "The owner asks which branch is underperforming and why.",
    ["Owner", "Manager"],
    ["Open the dashboard's branch comparison", "Spot the weaker branch", "Cross-check its low-stock list in inventory", "Discuss the stock-to-sales connection"],
    "Branch questions get answered in one screen instead of three phone calls.",
    ["How do you compare branches today?", "How old are the numbers you decide on?"],
    "Real multi-branch visibility — a top reason SMEs outgrow spreadsheets."),
  s("doc-expiry", "The permit that almost lapsed", "Document expiration", ["documents"],
    "Document demo seeded with items nearing expiry.",
    "A business permit expires in two weeks.",
    ["Admin", "Manager"],
    ["Open the register and show upcoming expirations", "Open the expiring permit", "Assign the renewal with a note", "Mark it Submitted after 'renewal'"],
    "Renewals start on time because the system watched the calendar.",
    ["What expired unnoticed in the last year?", "What did the penalty or rush cost?"],
    "Penalty avoidance — pure saved money and stress."),
  s("repeat-customer", "The regular who feels remembered", "Repeat customer", ["membership", "crm"],
    "Membership demo seeded with active and expiring members.",
    "A regular walks in near their package's end.",
    ["Staff", "Customer"],
    ["Look up the member and their remaining sessions", "Show the expiring-soon flag", "Record today's visit", "Show the simulated renewal reminder"],
    "The regular is greeted by name, balance known, renewal offered naturally.",
    ["How do you track packages and points today?", "How many members quietly lapsed last year?"],
    "Retention — keeping a customer is cheaper than finding one."),
  s("data-entry-error", "The typo that used to multiply", "Data-entry error", ["ordering", "universal"],
    "Order demo seeded with orders and line items.",
    "A quantity was entered wrong on an order.",
    ["Staff", "Manager"],
    ["Open the order and spot the wrong line", "Edit the line item; totals recompute automatically", "Show the change recorded in activity history", "Contrast with a hand-written correction chain"],
    "One correction in one place, with a record — instead of chasing every copy.",
    ["Where does the same data get typed twice today?", "What was your most expensive typo?"],
    "Enter once, correct once — error costs stop multiplying."),
  s("escalation", "The issue the manager saw in time", "Manager escalation", ["maintenance", "approvals"],
    "Ticket demo with an aging high-priority ticket.",
    "A critical ticket has waited past its target.",
    ["Staff", "Manager", "Owner"],
    ["Filter tickets by priority and age", "Open the overdue critical ticket", "Reassign it and add an escalation note", "Show the conceptual escalation placeholder for production rules"],
    "Aging critical work surfaces to management before the customer explodes.",
    ["How would a manager notice a stuck problem today?", "Who is the escalation path?"],
    "Management by exception — attention lands where it's needed."),
];
