import type { DeliveryModelRule } from "../types";

// Seed values are INTERNAL PLACEHOLDERS, not researched market prices.
// pricingSource: "Internal placeholder — owner verification required"

export const DELIVERY_MODELS: DeliveryModelRule[] = [
  {
    id: "shared-saas",
    name: "Shared SaaS",
    description:
      "A standardized multi-client platform where the agency retains ownership of the application and sells subscriptions to multiple businesses.",
    typicalCharges: [
      "One-time setup fee",
      "Monthly subscription",
      "Additional users",
      "Additional branches",
      "Optional modules",
      "Usage-based services",
    ],
    ownership: "Agency owns the platform",
    reusability: "Fully reusable across clients",
    initialCostTendency: "Low",
    monthlyCostTendency: "Moderate",
    customizationLevel: "Standard features only",
    recommendedFor: "Solo operators, micro and small businesses starting out",
    sourceCodeAvailability: "Not available",
    exclusivity: "None — shared platform",
    maintenanceResponsibility: "Agency",
    baseSetup: { minimum: 15000, maximum: 30000 },
    baseMonthly: { minimum: 2500, maximum: 4000 },
    moduleSetupFactor: 0.6,
    moduleMonthlyFactor: 1.0,
  },
  {
    id: "configured-saas",
    name: "Configured SaaS",
    description:
      "A shared SaaS platform configured for the client's terminology, fields, workflow, roles, reports, branding, and operational process.",
    typicalCharges: [
      "Implementation and configuration fee",
      "Monthly subscription",
      "Additional customization",
      "Optional integrations",
      "Training and migration",
    ],
    ownership: "Agency owns the platform",
    reusability: "Platform reusable; configuration is client-specific",
    initialCostTendency: "Moderate",
    monthlyCostTendency: "Moderate",
    customizationLevel: "Terminology, forms, workflow, roles, branding",
    recommendedFor: "Small and medium businesses with established processes",
    sourceCodeAvailability: "Not available",
    exclusivity: "None — shared platform",
    maintenanceResponsibility: "Agency",
    baseSetup: { minimum: 35000, maximum: 60000 },
    baseMonthly: { minimum: 3500, maximum: 6000 },
    moduleSetupFactor: 1.0,
    moduleMonthlyFactor: 1.1,
  },
  {
    id: "custom-built",
    name: "Custom-Built System",
    description:
      "A system developed specifically for one client's approved requirements, workflows, reports, integrations, roles, and deployment needs.",
    typicalCharges: [
      "Paid discovery",
      "Design",
      "Development",
      "Testing",
      "Deployment",
      "Training",
      "Maintenance and support",
    ],
    ownership: "Negotiated (typically client-licensed)",
    reusability: "Built for one client",
    initialCostTendency: "High",
    monthlyCostTendency: "Lower subscription, maintenance-based",
    customizationLevel: "Fully custom",
    recommendedFor: "Established businesses with unique, stable processes",
    sourceCodeAvailability: "Negotiable",
    exclusivity: "Effectively exclusive workflows",
    maintenanceResponsibility: "Agency via maintenance agreement",
    baseSetup: { minimum: 120000, maximum: 250000 },
    baseMonthly: { minimum: 2000, maximum: 5000 },
    moduleSetupFactor: 2.2,
    moduleMonthlyFactor: 0.4,
    maintenancePctMonthly: 1.25,
  },
  {
    id: "white-label",
    name: "White-Label Platform",
    description:
      "The agency owns the platform, but the client or partner operates it using their branding, domain, and client-facing identity.",
    typicalCharges: [
      "White-label setup fee",
      "Licensing fee",
      "Monthly minimum",
      "Tenant or client fees",
      "Support and hosting",
    ],
    ownership: "Agency owns; partner operates under their brand",
    reusability: "Platform reusable; branding per partner",
    initialCostTendency: "Moderate to high",
    monthlyCostTendency: "Higher (monthly minimum applies)",
    customizationLevel: "Branding, domain, tenant configuration",
    recommendedFor: "Partners reselling to their own client base",
    sourceCodeAvailability: "Not available",
    exclusivity: "Brand-level exclusivity only",
    maintenanceResponsibility: "Agency",
    baseSetup: { minimum: 60000, maximum: 120000 },
    baseMonthly: { minimum: 8000, maximum: 15000 },
    moduleSetupFactor: 1.2,
    moduleMonthlyFactor: 1.3,
  },
  {
    id: "exclusive-source-transfer",
    name: "Exclusive Build with Source-Code Transfer",
    description:
      "A premium option in which the client may receive source code, ownership rights, exclusivity, deployment documentation, or restrictions on resale.",
    typicalCharges: [
      "Full development cost",
      "Source-code transfer premium",
      "Exclusivity premium",
      "Documentation",
      "Deployment",
      "Warranty and maintenance options",
    ],
    ownership: "Client (per signed transfer agreement)",
    reusability: "Agency resale restricted per agreement",
    initialCostTendency: "Highest",
    monthlyCostTendency: "Low / optional maintenance",
    customizationLevel: "Fully custom",
    recommendedFor: "Enterprises requiring ownership and exclusivity",
    sourceCodeAvailability: "Included (per agreement)",
    exclusivity: "Contractual exclusivity available",
    maintenanceResponsibility: "Client, or agency via optional agreement",
    baseSetup: { minimum: 180000, maximum: 400000 },
    baseMonthly: { minimum: 2000, maximum: 6000 },
    moduleSetupFactor: 2.6,
    moduleMonthlyFactor: 0.3,
    maintenancePctMonthly: 1.0,
    sourceCodePremiumPct: 25,
    exclusivityPremiumPct: 20,
  },
];
