import type { DemoModuleType } from "../../types";
import type { FeatureValueExplanation } from "../types";

// Business-value explanations per demo-module type. The service's own
// "problem" text comes from the catalog; everything below is generated
// explanatory language and is labeled in the UI:
// "AI-generated business explanation — verify with client."

const f = (
  whatItIs: string,
  workflowImprovement: string,
  operationalBenefit: string,
  managementBenefit: string,
  customerBenefit: string,
  employeeBenefit: string,
): FeatureValueExplanation => ({ whatItIs, workflowImprovement, operationalBenefit, managementBenefit, customerBenefit, employeeBenefit });

export const FEATURE_VALUE: Record<DemoModuleType, FeatureValueExplanation> = {
  crm: f(
    "A central record of every inquiry and customer from first contact onward.",
    "Inquiries become tracked leads with owners instead of scattered chat messages.",
    "Fewer lost inquiries and faster, consistent follow-ups.",
    "A visible pipeline showing where every deal stands and why deals are lost.",
    "Customers get faster responses and never repeat their story.",
    "Staff know exactly which follow-ups are theirs today.",
  ),
  booking: f(
    "A shared schedule where requests become confirmed, assigned bookings.",
    "Bookings move from notebooks and chats into one conflict-checked calendar.",
    "Fewer double-bookings and no-shows; fuller utilization of each day.",
    "A live view of upcoming load for staffing decisions.",
    "Customers get confirmations and simulated reminders instead of silence.",
    "Staff see their day at a glance instead of asking around.",
  ),
  inventory: f(
    "A live stock list with quantities, reorder levels, and movement history.",
    "Stock changes are recorded as they happen instead of counted after the fact.",
    "Earlier low-stock warnings and fewer emergency purchases.",
    "Trustworthy counts for purchasing and loss-control decisions.",
    "Customers find what they came for in stock more often.",
    "Staff stop recounting shelves to answer simple questions.",
  ),
  ordering: f(
    "An order workbench with line items, automatic totals, and fulfillment statuses.",
    "Orders are encoded once and tracked to completion instead of retyped.",
    "Fewer order-taking errors and clearer daily fulfillment.",
    "A same-day sales picture without manual tallies.",
    "Customers get accurate orders and clear status.",
    "Staff spend less time re-checking amounts and chasing papers.",
  ),
  procurement: f(
    "A purchase-order workflow from request through approval to receiving.",
    "Purchases move through a documented approval queue instead of verbal requests.",
    "Fewer duplicate or forgotten orders; visible pending deliveries.",
    "Documented spending with price history per supplier.",
    "Customers see fewer stock-outs caused by late reordering.",
    "Staff know which requests are approved without chasing the owner.",
  ),
  quotation: f(
    "A quotation builder with line items, automatic totals, and an approval trail.",
    "Quotes are assembled from standard items instead of rebuilt in spreadsheets.",
    "Faster quote turnaround with consistent pricing.",
    "Win/loss visibility and a follow-up list of pending quotes.",
    "Customers receive professional, itemized quotations quickly.",
    "Staff stop recomputing totals and hunting old quotes for reference.",
  ),
  projects: f(
    "A job board tracking work from intake to completion with owners and stages.",
    "Every job has a record, an assignee, and a visible stage instead of living in memory.",
    "Instant status answers and earlier warnings on stalled work.",
    "Workload and bottleneck visibility across the team.",
    "Customers can be told exactly where their job stands.",
    "Staff have a clear queue and a record of what they accomplished.",
  ),
  portal: f(
    "A self-service view where clients see their own requests and statuses.",
    "Status is updated once in the system instead of answered call by call.",
    "Far fewer repetitive status inquiries reaching staff.",
    "Consistent, professional client communication.",
    "Customers check status anytime without calling.",
    "Staff interruptions drop noticeably.",
  ),
  approvals: f(
    "A structured approval queue with decisions, deciders, and remarks recorded.",
    "Approvals move from chat threads into a documented queue.",
    "Faster routine approvals and no stalled invisible requests.",
    "A decision trail that survives staff turnover and disputes.",
    "Customers wait less for approval-gated steps.",
    "Staff know exactly who to wait on and what was decided.",
  ),
  scheduling: f(
    "A shift planner with assignments and attendance records.",
    "Schedules are planned and changed in one place instead of whiteboards.",
    "Coverage gaps and shift clashes surface before they happen.",
    "Clean attendance records and fair shift distribution.",
    "Customers experience properly staffed service hours.",
    "Staff see their schedule early and disputes drop.",
  ),
  tasks: f(
    "A task board with owners, due dates, and completion tracking.",
    "Verbal instructions become assigned, checkable tasks.",
    "Routine checklists actually get completed and proven.",
    "Real-time visibility of what is done and what slipped.",
    "Customers benefit from consistent, complete routines.",
    "Staff have clarity on what is theirs and when it is due.",
  ),
  documents: f(
    "A document register with owners, deadlines, and expiry tracking.",
    "Requirements are tracked to completion instead of chased through folders.",
    "No more surprise expirations or missing requirements.",
    "Audit readiness and clear ownership of each document.",
    "Customers complete requirements faster with clear checklists.",
    "Staff stop digging through drawers and drives.",
  ),
  delivery: f(
    "A dispatch board tracking deliveries from preparation to proof of delivery.",
    "Dispatch moves from phone calls to visible statuses per delivery.",
    "Live visibility of every delivery and documented receipt.",
    "Driver accountability and fewer failed deliveries.",
    "Customers know when their delivery is coming and that it arrived.",
    "Drivers get clear assignments instead of radio confusion.",
  ),
  maintenance: f(
    "A ticket queue where issues are logged, prioritized, and resolved.",
    "Reported issues become tracked tickets instead of hallway mentions.",
    "No reported issue slips through; recurring problems become visible.",
    "Repair history per asset supports replace-or-repair decisions.",
    "Customers see their complaints acknowledged and resolved.",
    "Staff work a clear priority queue with resolution records.",
  ),
  membership: f(
    "A member register tracking plans, balances, points, and renewals.",
    "Package balances move from notebooks into accurate per-member records.",
    "Renewals stop lapsing silently; balances stop being disputed.",
    "Repeat-business levers become measurable.",
    "Customers trust their balances and get renewal reminders.",
    "Staff answer balance questions instantly.",
  ),
  learning: f(
    "An enrollment tracker covering registration, attendance, and completion.",
    "Enrollment lists and attendance move from sheets to per-person records.",
    "Clean completion records and no missed certificates.",
    "Per-batch progress reporting without manual assembly.",
    "Learners see clear progress and receive their completions.",
    "Trainers stop reconstructing attendance after the fact.",
  ),
  billing: f(
    "A billing monitor listing charges, due dates, and collection status.",
    "Who-owes-what moves from receipts and memory to a live list.",
    "Earlier, systematic follow-ups on overdue accounts.",
    "A clear receivables picture for cash planning.",
    "Customers get accurate, timely statements.",
    "Staff follow a list instead of awkward guesswork.",
  ),
  dashboard: f(
    "A management dashboard with headline cards and trend charts.",
    "Reports assemble themselves from daily records instead of month-end spreadsheets.",
    "Hours of report preparation disappear.",
    "Dips and spikes surface in days, not weeks.",
    "Customers benefit from faster, better-informed service decisions.",
    "Staff stop compiling numbers by hand every period.",
  ),
  production: f(
    "A batch tracker recording targets, output, rejects, and quality remarks.",
    "Production runs move from clipboards to traceable batch records.",
    "Yields and rejects become visible per batch.",
    "Quality drift is caught early; planning uses real numbers.",
    "Customers receive more consistent product quality.",
    "Operators log once instead of transcribing clipboards.",
  ),
  universal: f(
    "A configurable record-and-status workflow shaped to the process.",
    "An improvised process gains consistent records, stages, and owners.",
    "One agreed way of working, visible to everyone.",
    "Status and history on demand for any tracked process.",
    "Customers experience a more consistent, reliable process.",
    "Staff stop reinventing the process each time.",
  ),
};
